### ISSUE TITLE
Doesn't update package.json file

### ISSUE THREAD

**Issue by alexisab** [jadjoubran/webdash-package-json#9]
When we update a package from wedash with webdash-package-json it updates the package but doesn't update the `package.json` file. 

Is it an expected behavior ?

Webdash : 
![webdash_update](https://user-images.githubusercontent.com/11648546/38301392-b178aff0-37ff-11e8-92b7-cc37bd845cc3.PNG)

dotenv `package.json` : 
![package_update](https://user-images.githubusercontent.com/11648546/38301398-b8033250-37ff-11e8-8436-3a3d0725cc60.PNG)

my project `package.json`  : 
![package_json_not_updated](https://user-images.githubusercontent.com/11648546/38301427-ce4df798-37ff-11e8-88e0-5561d87081ba.PNG)

node: v9.4.0
yarn: v1.5.1
webdash: v1.3.4
webdash-package-json: v1.3.1

**Comment by jadjoubran** [comment]
Thanks @alexisab!
I first thought this is a bug too but I think it makes sense the way it is, explanation:

updating a package should not change your `package.json constraint` however it should simply update the package.
I believe this was reflected in `package-lock.json`, can you please confirm?
If so, when you push these changes to your team members and they run `npm install`, they will get the same version as you did
and at the end of the day, they all satisfy the same version constraint you setup, which is in this case `^5.0.0`
Let me know!

**Comment by alexisab** [comment]
Yes it has been updated in my `yarn.lock` file : 
```
dotenv@^5.0.0:
  version "5.0.1"
  resolved "https://registry.yarnpkg.com/dotenv/-/dotenv-5.0.1.tgz#a5317459bd3d79ab88cff6e44057a6a3fbb1fcef"
```

Thanks !
